language: minimal

services:
  - docker

install:
- docker pull jjmerelo/test-perl6

script: docker run -t -v $(pwd):/test --entrypoint /bin/sh jjmerelo/test-perl6 -c "perl6 -v && apk add --update --no-cache make gcc libc-dev && zef install --deps-only . && zef build ."
